# -*- coding: utf-8 -*-
"""part 2b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wA6cG86kq3Zx4SHGboJibyzuMlGl1vWd
"""

# Install packages
!pip install netCDF4 astropy

from netCDF4 import Dataset

# Change this to your MAG filename
mag_file = "L2_AL1_MAG_20260607_V00.nc"

ds = Dataset(mag_file)

print("Variables:")
print(ds.variables.keys())

# ==========================================
# PART 2B
# SUIT + MAG Correlation Analysis
# ==========================================

!pip install astropy netCDF4 scikit-image scipy

import numpy as np
import matplotlib.pyplot as plt

from astropy.io import fits
from netCDF4 import Dataset

from skimage.filters import threshold_otsu
from scipy.stats import pearsonr

#############################################
# Load SUIT FITS Image
#############################################

fits_file = "SUT_T26_0961_002231_Lev1.0_2026-06-29T22.11.24.936_08B3NB07.fits"

hdul = fits.open(fits_file)

image = None

for hdu in hdul:
    if hdu.data is not None:
        if len(hdu.data.shape) >= 2:
            image = hdu.data.astype(float)
            break

hdul.close()

#############################################
# Preprocess Image
#############################################

image = np.nan_to_num(image)

image = image - np.min(image)

image = image / np.max(image)

#############################################
# Active Region Segmentation
#############################################

threshold = threshold_otsu(image)

mask = image > threshold

#############################################
# Mean Active Region Intensity
#############################################

mean_intensity = np.mean(image[mask])

print("Mean Active Region Intensity =", mean_intensity)

#############################################
# Display Active Region
#############################################

plt.figure(figsize=(6,6))
plt.imshow(mask,cmap='gray')
plt.title("Detected Active Region")
plt.axis("off")
plt.show()

#############################################
# Load MAG Data
#############################################

mag_file = "L2_AL1_MAG_20260607_V00.nc"

ds = Dataset(mag_file)

Bx = ds.variables['Bx_gse'][:]
By = ds.variables['By_gse'][:]
Bz = ds.variables['Bz_gse'][:]

#############################################
# Magnetic Field Magnitude
#############################################

B = np.sqrt(Bx**2 + By**2 + Bz**2)

print("Mean Magnetic Field =", np.mean(B))

#############################################
# Correlation
#############################################

# Repeat intensity value
I = np.full(len(B),mean_intensity)

r,p = pearsonr(I,B)

print("Pearson Correlation =",r)

#############################################
# Scatter Plot
#############################################

plt.figure(figsize=(7,5))

plt.scatter(I,B,s=10)

plt.xlabel("Mean Active Region Intensity")

plt.ylabel("Magnetic Field Magnitude (nT)")

plt.title("Intensity vs Magnetic Field")

plt.grid(True)

plt.show()