# -*- coding: utf-8 -*-
"""part 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VD-CdvN77BZRhHdBdQ3cXiZ77v24zfXL
"""

!pip install sunpy astropy scikit-image matplotlib



"""# Solar Image Analysis Using Aditya-L1 Data

## Import Libraries

## Load FITS File

## Display Metadata

## Image Preprocessing

## Active Region Detection

## Visualization

## Conclusion
"""

import sunpy.map
import matplotlib.pyplot as plt

# Load the FITS file
smap = sunpy.map.Map('your_file.fits')  # replace with your actual filename

# Plot it
plt.figure(figsize=(8,8))
smap.plot()
plt.colorbar()
plt.title('Aditya-L1 SUIT - Dec 31 2023 X5 Flare')
plt.savefig('solar_image.png')
plt.show()

print("Date:", smap.date)
print("Instrument:", smap.instrument)
print("Image shape:", smap.data.shape)

print("Date:", smap.date)
print("Instrument:", smap.instrument)
print("Dimensions:", smap.dimensions)
print("Wavelength:", smap.wavelength)

!pip install "sunpy[map]" reproject mpl-animators

!pip install "sunpy[map]" reproject mpl-animators

import sunpy.map
import matplotlib.pyplot as plt

print("Import successful! ✅")

smap = sunpy.map.Map('/content/your_actual_filename.fits')

plt.figure(figsize=(8,8))
smap.plot()
plt.colorbar()
plt.title('Aditya-L1 SUIT - Dec 31 2023 X5 Flare')
plt.savefig('solar_image.png')
plt.show()

print("Date:", smap.date)
print("Instrument:", smap.instrument)

smap = sunpy.map.Map('/content/suit_2026Jun12T162910737.fits')

plt.figure(figsize=(8,8))
smap.plot()
plt.colorbar()
plt.title('Aditya-L1 SUIT - Dec 31 2023 X5 Flare')
plt.savefig('solar_image.png')
plt.show()

print("Date:", smap.date)
print("Instrument:", smap.instrument)

import matplotlib.pyplot as plt
import sunpy.map

smap = sunpy.map.Map("Suit_2026Jun12T162910737.fits")

plt.figure(figsize=(8,8))

smap.plot()

plt.colorbar()

plt.title("Aditya-L1 SUIT Solar Image")

plt.show()

print("Date:", smap.date)
print("Instrument:", smap.instrument)

import os
print(os.listdir())

!unzip suit_2026Jun12T162910737.zip

import os
print(os.listdir())

import matplotlib.pyplot as plt
import sunpy.map

smap = sunpy.map.Map("SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits")

plt.figure(figsize=(8,8))

smap.plot()

plt.colorbar()

plt.title("Aditya-L1 SUIT Solar Image")

plt.show()

print("Date:", smap.date)
print("Instrument:", smap.instrument)

print("Date:", smap.date)
print("Instrument:", smap.instrument)
print("Dimensions:", smap.dimensions)
print("Wavelength:", smap.wavelength)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,8))

smap.plot(cmap='inferno')

plt.colorbar()

plt.title("Enhanced SUIT Solar Image")

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Image data
data = smap.data

# Threshold value
threshold = np.mean(data) + 2*np.std(data)

# Active region mask
active_regions = data > threshold

# Plot
plt.figure(figsize=(8,8))
plt.imshow(active_regions, cmap='gray')
plt.title("Detected Active Regions")
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

data = smap.data

# Lower threshold
threshold = np.mean(data) + 0.5*np.std(data)

# Detect regions
active_regions = data > threshold

# Plot
plt.figure(figsize=(8,8))
plt.imshow(active_regions, cmap='hot')
plt.title("Improved Active Region Detection")
plt.colorbar()
plt.show()

from scipy import ndimage
import matplotlib.pyplot as plt

# Label connected regions
labeled, num_regions = ndimage.label(active_regions)

print("Number of Active Regions:", num_regions)

# Show labeled regions
plt.figure(figsize=(8,8))
plt.imshow(labeled, cmap='nipy_spectral')
plt.title("Labeled Active Regions")
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt
from scipy import ndimage
from matplotlib.patches import Rectangle

# Create figure
fig, ax = plt.subplots(figsize=(8,8))

# Show original image
ax.imshow(data, cmap='inferno')

# Find objects
objects = ndimage.find_objects(labeled)

# Draw boxes
for obj in objects:
    if obj is not None:
        y, x = obj

        rect = Rectangle(
            (x.start, y.start),
            x.stop - x.start,
            y.stop - y.start,
            edgecolor='cyan',
            facecolor='none',
            linewidth=2
        )

        ax.add_patch(rect)

plt.title("Active Regions with Bounding Boxes")
plt.show()

plt.figure(figsize=(8,8))
plt.imshow(data, cmap='inferno')
plt.title("Final Solar Analysis")

# Save image
plt.savefig("final_result.png")

plt.show()

print("Image saved successfully")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,8))
plt.imshow(data, cmap='inferno')
plt.title("Final Solar Analysis")

# Save image
plt.savefig("final_result.png")

plt.show()

print("Image saved successfully")

import sunpy.map
import matplotlib.pyplot as plt

# Open FITS file
smap = sunpy.map.Map("SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits")

# Get image data
data = smap.data

# Plot image
plt.figure(figsize=(8,8))
plt.imshow(data, cmap='inferno')

plt.title("Final Solar Analysis")

# Save image
plt.savefig("final_result.png")

plt.show()

print("Image saved successfully")

!pip install sunpy astropy matplotlib reproject mpl-animators

import sunpy.map
import matplotlib.pyplot as plt

# Open FITS file
smap = sunpy.map.Map("SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits")

# Get image data
data = smap.data

# Plot image
plt.figure(figsize=(8,8))
plt.imshow(data, cmap='inferno')

plt.title("Final Solar Analysis")

# Save image
plt.savefig("final_result.png")

plt.show()

print("Image saved successfully")

import os
print(os.listdir())

!unzip suit_2026Jun12T162910737.zip

import os
print(os.listdir())

import os
print(os.listdir())

!unzip suit_2026Jun12T162910737.zip

import sunpy.map
import matplotlib.pyplot as plt

# Open FITS file
smap = sunpy.map.Map("SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits")

# Extract image data
data = smap.data

# Create figure
plt.figure(figsize=(8,8))

# Show image
plt.imshow(data, cmap='inferno')

# Add title
plt.title("Final Solar Analysis")

# Save image
plt.savefig("final_result.png")

# Display image
plt.show()

print("Image saved successfully")

import sunpy.map
import matplotlib.pyplot as plt

smap = sunpy.map.Map("SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits")

data = smap.data

plt.figure(figsize=(8,8))
plt.imshow(data, cmap='inferno')

plt.title("Final Solar Analysis")

plt.savefig("final_result.png")

plt.show()

print("Image saved successfully")

import os
print(os.listdir())

!unzip suit_2026Jun12T162910737.zip

import os
print(os.listdir())

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir())

!unzip suit_2026Jun12T162910737.zip

import sunpy.map
import matplotlib.pyplot as plt

# Open FITS file
smap = sunpy.map.Map("SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits")

# Extract image data
data = smap.data

# Create figure
plt.figure(figsize=(8,8))

# Show image
plt.imshow(data, cmap='inferno')

# Add title
plt.title("Final Solar Analysis")

# Save image
plt.savefig("final_result.png")

# Display image
plt.show()

print("Image saved successfully")

!pip install sunpy astropy matplotlib reproject mpl-animators

import sunpy.map
import matplotlib.pyplot as plt

# Open FITS file
smap = sunpy.map.Map("SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits")

# Extract image data
data = smap.data

# Create figure
plt.figure(figsize=(8,8))

# Show image
plt.imshow(data, cmap='inferno')

# Add title
plt.title("Final Solar Analysis")

# Save image
plt.savefig("final_result.png")

# Display image
plt.show()

print("Image saved successfully")

import sunpy.map
import matplotlib.pyplot as plt

# Open FITS file
smap = sunpy.map.Map("SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits")

# Get image data
data = smap.data

# Plot image
plt.figure(figsize=(8,8))
plt.imshow(data, cmap='inferno')

plt.title("Final Solar Analysis")

# Save image
plt.savefig("final_result.png")

# Show image
plt.show()

print("Image saved successfully")

import zipfile

with zipfile.ZipFile("suit_2026Jun12T162910737.zip", "r") as zip_ref:
    zip_ref.extractall()

print("ZIP file extracted successfully!")

import os

print(os.listdir())

import os

print(os.listdir())

import sunpy.map

smap = sunpy.map.Map("SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits")

!pip install sunpy[all]

import sunpy
print(sunpy.__version__)

import sunpy.map

smap = sunpy.map.Map(
    "SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits"
)

print("Date:", smap.date)
print("Instrument:", smap.instrument)
print("Dimensions:", smap.dimensions)
print("Wavelength:", smap.wavelength)

import sunpy.map

smap = sunpy.map.Map(
    "SUT_T26_0723_002181_Lev1.0_2026-05-25T21.09.53.750_0973NB07.fits"
)

print("Date:", smap.date)
print("Instrument:", smap.instrument)
print("Dimensions:", smap.dimensions)
print("Wavelength:", smap.wavelength)

from skimage.filters import threshold_otsu
import matplotlib.pyplot as plt

# Get image data
data = smap.data

# Find threshold value
threshold = threshold_otsu(data)

# Create binary mask
mask = data > threshold

# Display active regions
plt.figure(figsize=(8,8))
plt.imshow(mask, cmap='gray')
plt.title("Active Region Detection")
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,8))

# Show original solar image
plt.imshow(data, cmap='inferno')

# Draw active region boundary
plt.contour(mask, colors='cyan', linewidths=1)

plt.title("Detected Active Regions on Solar Image")
plt.colorbar(label="Intensity")
plt.show()

plt.figure(figsize=(8,8))

# Original image
plt.imshow(data, cmap='inferno')

# Active region boundary
plt.contour(mask, colors='cyan', linewidths=1)

plt.title("Detected Active Regions on Solar Image")

plt.show()

plt.figure(figsize=(8,8))

im = plt.imshow(data, cmap='inferno')

plt.contour(mask, colors='cyan', linewidths=1)

plt.title("Final Solar Analysis")

plt.colorbar(im, label="Intensity")

plt.savefig("final_result.png", dpi=300)

plt.show()

"""## Conclusion

The Aditya-L1 SUIT FITS image acquired on 25 May 2026 was successfully processed using SunPy, Astropy, NumPy, and Matplotlib. Image preprocessing techniques such as intensity clipping and logarithmic scaling improved the visibility of solar structures. Threshold segmentation enabled the identification of active regions, and contour overlay provided clear visualization of their boundaries. This work demonstrates the application of astronomical image processing techniques for analyzing solar activity and contributes to understanding the dynamic behavior of the Sun.
"""

